Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t4g.micro
    AllowedValues:
      - t2.micro
      - t4g.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"  
#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html

Mappings: 
  RegionMap: 
    ap-northeast-1:
      HVM64: ami-0404778e217f54308
      HVMG2: ami-0a584ac55a7631c0c
    us-east-1:
      HVM64: ami-04902260ca3d33422
      HVMG2: ami-066ee5fd4a9ef77f1
    ap-south-1:
      HVM64: ami-0bb4b6f704a33803c
      HVMG2: ami-0a7c483d527806435
    ap-southeast-1:
      HVM64: ami-08569b978cc4dfa10
      HVMG2: ami-0be9df32ae9f92309

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceTypeParameter
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      KeyName:
        Ref: myKeyPair
      Tags:
        - Key: Name
          Value: !Ref "AWS::Region"

Outputs:
  MyStacksRegion:
    Value: !Ref "AWS::Region"
  InstanceId:
    Value: !Ref Ec2Instance
    Description: node for galera cluster 
  awsacId:
    Value: !Ref "AWS::AccountId"



    #AMI
    # template